poipoipoipaciao sono federico cciao
	lfkjds
	lkjasfd
    			lkjdfs
l = """Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaofinalmente posso modificare un mio filewooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
CCCCCCCCCCCCCiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooCCCCCCCCCCCiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Come
Stai"""
a
a
aciao adesso funxztiona
a
a
a
a
aa
a
a
a
acaio cpoipoi
a
a
a
a
aa
a
a
a
a
a
aa
apotrebbe essere che ci siano dei progl
