jjkkkkkkkoipoipoiaaaaaaaaaaaaasssssssssssssssssssssssssssssssssssssssssscccccc:wqssdsdsfdsfciao come stai?cccccccccccccccccccccccccccccciaosdfddffsdapoipoipoipaciao sono federico cciao
	lfkjds
	lkjsdfasfd
fsdlkjflsdkjflskdjf    			lkjdfs
l = "Ciaoooooooooooooooooooooooooooooooooooooooooooo
ssoooooooooooooooooooooooofdglkjdfgkjhdfkjghdfoooooooooooooooooooo
CiaooooooooooooooooooooooooooooooooooooooooooooCiaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaofinalmente posso modificare un mio filewooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
CCCCCCCCCCCCCiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooCCCCCCCCCCCiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
ComejjStaiaStaiaaaaaciao adesso funxztionauaciao adesso funxztiona
Staiaaaaacio adesso funxztionauaciao adesso funxztiona
aaaaciao adesso funxztionauaciao adesso funxztiona
aaciao adesso funxztionauaciao adesso funxztionaao adesso funxztionaaaaaaaaaaaaaaaaaaaaaaaaa
aciao adesso funxztionaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaio cpoipoi
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaio cpoipoi
aaaaaaaaaaaaaaaaaaaaaaaaio cpoipoi
aaaaaaaaaaio cpoipoi
aaaio cpoipoiaio cpoipoiaacaio cpoipoi
aio cpoipoiaacaio cpoipoi
aacaio cpoipoi
acaio cpoipoiaaaaiidslkjfaaaaa
aaaaiidslkjfaaaaa
aaaaa
aaaaaa
aaaaaaaaaaaaaa
aaaaaaaaa
aaaaaaa
aaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaa
aaaaaaa
aaapotrebbe essere che ci siano dei progl
apotrebbe essere che ci siano dei progl
