
	lfkjds
	lkjasfd
    			lkjdfs
l = """Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
CCCCCCCCCCCCCiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooCCCCCCCCCCCiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaooooooooooooooooooooooooooooooooooooooooooooiaoooooooooooooooooooooooooooooooooooooooooooo
Ciaoooooooooooooooooooooooooooooooooooooooooooo
Come
Stai"""
a
a
a
a
a
a
a
a
a










aaa





























aaa
